dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.3
  path: ^1.9.0
  webview_flutter: ^4.7.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  sqflite: ^2.3.3+1
  connectivity_plus: ^6.0.3
  archive: ^3.6.1       # 用于纯 Dart 高性能解压 EPUB Zip 包
  xml: ^6.5.0           # 用于解析 container.xml 与 content.opf
  file_picker: ^8.0.0+1 # 用于系统文件选择器选取 TTF/OTF